user_id: 123456
url: http://192.168.30.238:8000/
skill_path: /api/v1/skills
add_user_skills_path: /api/v1/users/{user_id}/skills
view_user_skills_path: /api/v1/users/{user_id}/skills
del_user_skills_path: /api/v1/users/{user_id}/skills/{skill_name}
skill_user_id_param: user_id
list_user_skills_path: /api/v1/skills/custom

// 智能伙伴配置页面
view_partner_config_path: /api/v1/agent
update_partner_config_path: /api/v1/agent

//会话列表展示
view_chat_sessions_path: /api/v1/chat/sessions
del_chat_session_path: /api/v1/chat/sessions/{session_id}
create_chat_session_path: /api/v1/chat/sessions
get_chat_session_path: /api/v1/chat/sessions/{session_id}

//skill相关
upload_skill_path: /api/v1/skills/custom/upload
