user_id: 123456
url: http://localhost:8000/
//我添加的
skill_path: /api/v1/skills
add_user_skills_path: /api/v1/users/{user_id}/skills
view_user_skills_path: /api/v1/users/{user_id}/skills
del_user_skills_path: /api/v1/users/{user_id}/skills/{skill_name}
skill_user_id_param: user_id
//我创建的
list_user_skills_path: /api/v1/skills/custom
del_user_skill_path: /api/v1/skills/custom/{skill_name}



// 智能伙伴配置页面
view_partner_config_path: /api/v1/agent
update_partner_config_path: /api/v1/agent

//会话列表展示
view_chat_sessions_path: /api/v1/chat/sessions
del_chat_session_path: /api/v1/chat/sessions/{session_id}
create_chat_session_path: /api/v1/chat/sessions
get_chat_session_path: /api/v1/chat/sessions/{session_id}

//skill相关
upload_skill_path: /api/v1/skills/custom/upload

//查看生成的文件源码
view_generated_code_path: /api/v1/chat/sessions/{session_id}/files/preview
